//
// AppPostResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppPostResult: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var serverPath: String?

    public init(id: Int64? = nil, serverPath: String? = nil) {
        self.id = id
        self.serverPath = serverPath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case serverPath
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(serverPath, forKey: .serverPath)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AppPostResult: Identifiable {}
