//
// AppUserResetEmailRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppUserResetEmailRequest: Codable, JSONEncodable, Hashable {

    public static let codeRule = StringRule(minLength: 1, maxLength: nil, pattern: "/\\d{4,8}$/")
    /** 邮箱 */
    public var email: String?
    /** 邮箱验证码 */
    public var code: String

    public init(email: String? = nil, code: String) {
        self.email = email
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encode(code, forKey: .code)
    }
}

