//
// AppUserListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppUserListResponse: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var unionID: String?
    public var platform: String?
    public var userName: String?
    public var nickName: String?
    public var email: String?
    public var phone: String?
    public var avatar: String?
    public var role: String?
    public var roleID: Int64?
    public var createDate: Date?
    public var lastUpdate: Date?

    public init(id: Int64? = nil, unionID: String? = nil, platform: String? = nil, userName: String? = nil, nickName: String? = nil, email: String? = nil, phone: String? = nil, avatar: String? = nil, role: String? = nil, roleID: Int64? = nil, createDate: Date? = nil, lastUpdate: Date? = nil) {
        self.id = id
        self.unionID = unionID
        self.platform = platform
        self.userName = userName
        self.nickName = nickName
        self.email = email
        self.phone = phone
        self.avatar = avatar
        self.role = role
        self.roleID = roleID
        self.createDate = createDate
        self.lastUpdate = lastUpdate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case unionID
        case platform
        case userName
        case nickName
        case email
        case phone
        case avatar
        case role
        case roleID
        case createDate
        case lastUpdate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(unionID, forKey: .unionID)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(userName, forKey: .userName)
        try container.encodeIfPresent(nickName, forKey: .nickName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(roleID, forKey: .roleID)
        try container.encodeIfPresent(createDate, forKey: .createDate)
        try container.encodeIfPresent(lastUpdate, forKey: .lastUpdate)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AppUserListResponse: Identifiable {}
