//
// AuthorizeResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthorizeResult: Codable, JSONEncodable, Hashable {

    public var code: Int?
    public var error: String?
    public var accessToken: String?
    public var tokenType: String?
    public var expiresIn: Int64?

    public init(code: Int? = nil, error: String? = nil, accessToken: String? = nil, tokenType: String? = nil, expiresIn: Int64? = nil) {
        self.code = code
        self.error = error
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresIn = expiresIn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case error
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(tokenType, forKey: .tokenType)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
    }
}

