//
// CommonFriendModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CommonFriendModel: Codable, JSONEncodable, Hashable {

    /** 用户ID */
    public var userID: Int64?
    /** 昵称 */
    public var nickName: String?
    /** 头像 */
    public var avatar: String?

    public init(userID: Int64? = nil, nickName: String? = nil, avatar: String? = nil) {
        self.userID = userID
        self.nickName = nickName
        self.avatar = avatar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userID
        case nickName
        case avatar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userID, forKey: .userID)
        try container.encodeIfPresent(nickName, forKey: .nickName)
        try container.encodeIfPresent(avatar, forKey: .avatar)
    }
}

