//
// ContributeDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContributeDetail: Codable, JSONEncodable, Hashable {

    public var contributeAmount: String?
    public var contributeType: String?

    public init(contributeAmount: String? = nil, contributeType: String? = nil) {
        self.contributeAmount = contributeAmount
        self.contributeType = contributeType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contributeAmount
        case contributeType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contributeAmount, forKey: .contributeAmount)
        try container.encodeIfPresent(contributeType, forKey: .contributeType)
    }
}

