//
// CreateOrderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderRequest: Codable, JSONEncodable, Hashable {

    public static let amountRule = NumericRule<Double>(minimum: 0.01, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let productNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let productTypeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let productIDRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var amount: Double
    public var productName: String
    public var productType: String
    public var productID: String

    public init(amount: Double, productName: String, productType: String, productID: String) {
        self.amount = amount
        self.productName = productName
        self.productType = productType
        self.productID = productID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case productName
        case productType
        case productID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(productName, forKey: .productName)
        try container.encode(productType, forKey: .productType)
        try container.encode(productID, forKey: .productID)
    }
}

