//
// CreateOrderResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderResult: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var orderNo: String?

    public init(id: Int64? = nil, orderNo: String? = nil) {
        self.id = id
        self.orderNo = orderNo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case orderNo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(orderNo, forKey: .orderNo)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CreateOrderResult: Identifiable {}
