//
// CurrencyConsumeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CurrencyConsumeRequest: Codable, JSONEncodable, Hashable {

    public static let currencyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** 虚拟币代码 */
    public var currency: String
    /** 消费额 */
    public var balance: Int
    /** 备注 */
    public var remark: String?
    /** 描述 */
    public var description: String?
    /** 标签 */
    public var tags: String?

    public init(currency: String, balance: Int, remark: String? = nil, description: String? = nil, tags: String? = nil) {
        self.currency = currency
        self.balance = balance
        self.remark = remark
        self.description = description
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case balance
        case remark
        case description
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(balance, forKey: .balance)
        try container.encodeIfPresent(remark, forKey: .remark)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

