//
// EmailSignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmailSignInRequest: Codable, JSONEncodable, Hashable {

    public static let emailRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let verifyCodeRule = StringRule(minLength: 1, maxLength: nil, pattern: "/\\d{4,8}$/")
    public static let twoFactorCodeRule = StringRule(minLength: 6, maxLength: 6, pattern: "/^[0-9]*$/")
    /** 用户邮箱地址 */
    public var email: String
    /** 验证码，长度为4到8位的数字 */
    public var verifyCode: String
    /** 双因素认证代码，如果启用双因素认证登录，则必填 */
    public var twoFactorCode: String?

    public init(email: String, verifyCode: String, twoFactorCode: String? = nil) {
        self.email = email
        self.verifyCode = verifyCode
        self.twoFactorCode = twoFactorCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case verifyCode
        case twoFactorCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(verifyCode, forKey: .verifyCode)
        try container.encodeIfPresent(twoFactorCode, forKey: .twoFactorCode)
    }
}

