//
// EmailSignUpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmailSignUpRequest: Codable, JSONEncodable, Hashable {

    public static let emailRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let pwdRule = StringRule(minLength: 6, maxLength: 32, pattern: "/^[a-zA-Z0-9_\\-!@#$%^&*()]*$/")
    public static let emailCodeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/\\d{4,8}$/")
    public static let phoneRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(\\d{11})?$/")
    public static let phoneCodeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/\\d{4,8}$/")
    public static let nickNameRule = StringRule(minLength: 4, maxLength: 32, pattern: nil)
    public static let avatarRule = StringRule(minLength: nil, maxLength: 999, pattern: nil)
    public static let dataRule = StringRule(minLength: nil, maxLength: 9999, pattern: nil)
    /** 用户邮箱地址 */
    public var email: String
    /** 用户密码，长度为6到32个字符 */
    public var pwd: String
    /** 邮箱验证码 */
    public var emailCode: String?
    /** 手机号，必须为11位数字 */
    public var phone: String?
    /** 手机验证码（只有启用的手机验证码功能时，才需要传入） */
    public var phoneCode: String?
    /** 用户昵称 */
    public var nickName: String?
    /** 用户头像URL */
    public var avatar: String?
    /** 自定义数据 */
    public var data: String?

    public init(email: String, pwd: String, emailCode: String? = nil, phone: String? = nil, phoneCode: String? = nil, nickName: String? = nil, avatar: String? = nil, data: String? = nil) {
        self.email = email
        self.pwd = pwd
        self.emailCode = emailCode
        self.phone = phone
        self.phoneCode = phoneCode
        self.nickName = nickName
        self.avatar = avatar
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case pwd
        case emailCode
        case phone
        case phoneCode
        case nickName
        case avatar
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(pwd, forKey: .pwd)
        try container.encodeIfPresent(emailCode, forKey: .emailCode)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(phoneCode, forKey: .phoneCode)
        try container.encodeIfPresent(nickName, forKey: .nickName)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

