//
// EnterprisePayInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnterprisePayInfo: Codable, JSONEncodable, Hashable {

    public var bizInfo: String?
    public var invoiceAmount: String?
    public var isUseEnterprisePay: Bool?

    public init(bizInfo: String? = nil, invoiceAmount: String? = nil, isUseEnterprisePay: Bool? = nil) {
        self.bizInfo = bizInfo
        self.invoiceAmount = invoiceAmount
        self.isUseEnterprisePay = isUseEnterprisePay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bizInfo
        case invoiceAmount
        case isUseEnterprisePay
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bizInfo, forKey: .bizInfo)
        try container.encodeIfPresent(invoiceAmount, forKey: .invoiceAmount)
        try container.encodeIfPresent(isUseEnterprisePay, forKey: .isUseEnterprisePay)
    }
}

