//
// ExchangeRatePutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExchangeRatePutRequest: Codable, JSONEncodable, Hashable {

    public var toCurrencyCode: String?
    public var exchangeRate: Int64?
    public var description: String?

    public init(toCurrencyCode: String? = nil, exchangeRate: Int64? = nil, description: String? = nil) {
        self.toCurrencyCode = toCurrencyCode
        self.exchangeRate = exchangeRate
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case toCurrencyCode
        case exchangeRate
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(toCurrencyCode, forKey: .toCurrencyCode)
        try container.encodeIfPresent(exchangeRate, forKey: .exchangeRate)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

