//
// ExternalAccountPutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExternalAccountPutRequest: Codable, JSONEncodable, Hashable {

    /** 头像 */
    public var avatar: String?
    /** 自定义数据 */
    public var data: String?
    /** 启用 */
    public var enable: Bool?

    public init(avatar: String? = nil, data: String? = nil, enable: Bool? = nil) {
        self.avatar = avatar
        self.data = data
        self.enable = enable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avatar
        case data
        case enable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(enable, forKey: .enable)
    }
}

