//
// FileListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FileListResult: Codable, JSONEncodable, Hashable {

    public var directories: [DirectoryItem]?
    public var files: [FileItem]?
    public var totalDirectories: Int?
    public var totalFiles: Int?
    public var size: Int64?

    public init(directories: [DirectoryItem]? = nil, files: [FileItem]? = nil, totalDirectories: Int? = nil, totalFiles: Int? = nil, size: Int64? = nil) {
        self.directories = directories
        self.files = files
        self.totalDirectories = totalDirectories
        self.totalFiles = totalFiles
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case directories
        case files
        case totalDirectories
        case totalFiles
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(directories, forKey: .directories)
        try container.encodeIfPresent(files, forKey: .files)
        try container.encodeIfPresent(totalDirectories, forKey: .totalDirectories)
        try container.encodeIfPresent(totalFiles, forKey: .totalFiles)
        try container.encodeIfPresent(size, forKey: .size)
    }
}

