//
// FollowerPutModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FollowerPutModel: Codable, JSONEncodable, Hashable {

    public var alias: String?
    public var closenessScore: Int64?
    public var attentionScore: Int64?
    public var tags: String?
    public var status: String?
    public var remark: String?

    public init(alias: String? = nil, closenessScore: Int64? = nil, attentionScore: Int64? = nil, tags: String? = nil, status: String? = nil, remark: String? = nil) {
        self.alias = alias
        self.closenessScore = closenessScore
        self.attentionScore = attentionScore
        self.tags = tags
        self.status = status
        self.remark = remark
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alias
        case closenessScore
        case attentionScore
        case tags
        case status
        case remark
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encodeIfPresent(closenessScore, forKey: .closenessScore)
        try container.encodeIfPresent(attentionScore, forKey: .attentionScore)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(remark, forKey: .remark)
    }
}

