//
// FollowerModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FollowerModel: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var targetUserID: Int64?
    public var alias: String?
    public var nickName: String?
    public var avatar: String?
    public var isMutual: Bool?
    public var closenessScore: Int64?
    public var attentionScore: Int64?
    public var tags: String?
    public var status: String?
    public var remark: String?
    public var createDate: Date?

    public init(id: Int64? = nil, targetUserID: Int64? = nil, alias: String? = nil, nickName: String? = nil, avatar: String? = nil, isMutual: Bool? = nil, closenessScore: Int64? = nil, attentionScore: Int64? = nil, tags: String? = nil, status: String? = nil, remark: String? = nil, createDate: Date? = nil) {
        self.id = id
        self.targetUserID = targetUserID
        self.alias = alias
        self.nickName = nickName
        self.avatar = avatar
        self.isMutual = isMutual
        self.closenessScore = closenessScore
        self.attentionScore = attentionScore
        self.tags = tags
        self.status = status
        self.remark = remark
        self.createDate = createDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case targetUserID
        case alias
        case nickName
        case avatar
        case isMutual
        case closenessScore
        case attentionScore
        case tags
        case status
        case remark
        case createDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(targetUserID, forKey: .targetUserID)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encodeIfPresent(nickName, forKey: .nickName)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(isMutual, forKey: .isMutual)
        try container.encodeIfPresent(closenessScore, forKey: .closenessScore)
        try container.encodeIfPresent(attentionScore, forKey: .attentionScore)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(remark, forKey: .remark)
        try container.encodeIfPresent(createDate, forKey: .createDate)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension FollowerModel: Identifiable {}
