//
// FulfillmentDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FulfillmentDetail: Codable, JSONEncodable, Hashable {

    public var fulfillmentAmount: String?
    public var gmtPayment: String?
    public var outRequestNo: String?

    public init(fulfillmentAmount: String? = nil, gmtPayment: String? = nil, outRequestNo: String? = nil) {
        self.fulfillmentAmount = fulfillmentAmount
        self.gmtPayment = gmtPayment
        self.outRequestNo = outRequestNo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fulfillmentAmount
        case gmtPayment
        case outRequestNo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fulfillmentAmount, forKey: .fulfillmentAmount)
        try container.encodeIfPresent(gmtPayment, forKey: .gmtPayment)
        try container.encodeIfPresent(outRequestNo, forKey: .outRequestNo)
    }
}

