//
// GoodsDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GoodsDetail: Codable, JSONEncodable, Hashable {

    public var alipayGoodsId: String?
    public var body: String?
    public var categoriesTree: String?
    public var goodsCategory: String?
    public var goodsId: String?
    public var goodsName: String?
    public var outItemId: String?
    public var outSkuId: String?
    public var price: String?
    public var quantity: Int64?
    public var showUrl: String?

    public init(alipayGoodsId: String? = nil, body: String? = nil, categoriesTree: String? = nil, goodsCategory: String? = nil, goodsId: String? = nil, goodsName: String? = nil, outItemId: String? = nil, outSkuId: String? = nil, price: String? = nil, quantity: Int64? = nil, showUrl: String? = nil) {
        self.alipayGoodsId = alipayGoodsId
        self.body = body
        self.categoriesTree = categoriesTree
        self.goodsCategory = goodsCategory
        self.goodsId = goodsId
        self.goodsName = goodsName
        self.outItemId = outItemId
        self.outSkuId = outSkuId
        self.price = price
        self.quantity = quantity
        self.showUrl = showUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alipayGoodsId
        case body
        case categoriesTree
        case goodsCategory
        case goodsId
        case goodsName
        case outItemId
        case outSkuId
        case price
        case quantity
        case showUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alipayGoodsId, forKey: .alipayGoodsId)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(categoriesTree, forKey: .categoriesTree)
        try container.encodeIfPresent(goodsCategory, forKey: .goodsCategory)
        try container.encodeIfPresent(goodsId, forKey: .goodsId)
        try container.encodeIfPresent(goodsName, forKey: .goodsName)
        try container.encodeIfPresent(outItemId, forKey: .outItemId)
        try container.encodeIfPresent(outSkuId, forKey: .outSkuId)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(showUrl, forKey: .showUrl)
    }
}

