//
// HbFqPayInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HbFqPayInfo: Codable, JSONEncodable, Hashable {

    public var fqAmount: String?
    public var userInstallNum: String?

    public init(fqAmount: String? = nil, userInstallNum: String? = nil) {
        self.fqAmount = fqAmount
        self.userInstallNum = userInstallNum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fqAmount
        case userInstallNum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fqAmount, forKey: .fqAmount)
        try container.encodeIfPresent(userInstallNum, forKey: .userInstallNum)
    }
}

