//
// MySqlGeometry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MySqlGeometry: Codable, JSONEncodable, Hashable {

    public var xCoordinate: Double?
    public var yCoordinate: Double?
    public var srid: Int?
    public var isNull: Bool?
    public var value: Data?

    public init(xCoordinate: Double? = nil, yCoordinate: Double? = nil, srid: Int? = nil, isNull: Bool? = nil, value: Data? = nil) {
        self.xCoordinate = xCoordinate
        self.yCoordinate = yCoordinate
        self.srid = srid
        self.isNull = isNull
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case xCoordinate
        case yCoordinate
        case srid
        case isNull
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(xCoordinate, forKey: .xCoordinate)
        try container.encodeIfPresent(yCoordinate, forKey: .yCoordinate)
        try container.encodeIfPresent(srid, forKey: .srid)
        try container.encodeIfPresent(isNull, forKey: .isNull)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

