//
// OAuthAccountSignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OAuthAccountSignInRequest: Codable, JSONEncodable, Hashable {

    public static let unionIDRule = StringRule(minLength: 1, maxLength: 50, pattern: "/^[a-zA-Z0-9_-]*$/")
    public static let platformRule = StringRule(minLength: 1, maxLength: 20, pattern: "/^[a-zA-Z0-9]*$/")
    public static let twoFactorCodeRule = StringRule(minLength: 6, maxLength: 6, pattern: "/^[0-9]*$/")
    /** UnionID，长度必须在1到50个字符之间，只能包含字母、数字、下划线和连字符 */
    public var unionID: String
    /** 平台，长度必须在1到20个字符之间，只能包含字母和数字 */
    public var platform: String
    /** 双因素认证代码，如果启用双因素认证登录，则必填，长度必须为6个字符，只能包含数字 */
    public var twoFactorCode: String?

    public init(unionID: String, platform: String, twoFactorCode: String? = nil) {
        self.unionID = unionID
        self.platform = platform
        self.twoFactorCode = twoFactorCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unionID
        case platform
        case twoFactorCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(unionID, forKey: .unionID)
        try container.encode(platform, forKey: .platform)
        try container.encodeIfPresent(twoFactorCode, forKey: .twoFactorCode)
    }
}

