//
// PaymentInfoWithId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentInfoWithId: Codable, JSONEncodable, Hashable {

    public var paymentIds: [String]?
    public var type: String?

    public init(paymentIds: [String]? = nil, type: String? = nil) {
        self.paymentIds = paymentIds
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paymentIds
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(paymentIds, forKey: .paymentIds)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

