//
// PhoneSignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PhoneSignInRequest: Codable, JSONEncodable, Hashable {

    public static let phoneRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let verifyCodeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var phone: String
    public var verifyCode: String
    /** 如果启用双因素认证登录，则必填 */
    public var twoFactorCode: String?

    public init(phone: String, verifyCode: String, twoFactorCode: String? = nil) {
        self.phone = phone
        self.verifyCode = verifyCode
        self.twoFactorCode = twoFactorCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case verifyCode
        case twoFactorCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(phone, forKey: .phone)
        try container.encode(verifyCode, forKey: .verifyCode)
        try container.encodeIfPresent(twoFactorCode, forKey: .twoFactorCode)
    }
}

