//
// ProfileResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProfileResult: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var unionID: String?
    public var phone: String?
    public var createDate: Date?
    public var userName: String?
    public var phoneIsValid: Bool?
    public var data: String?
    public var email: String?
    public var emailIsValid: Bool?
    public var lastUpdate: Date?
    public var nickName: String?
    public var avatar: String?
    public var role: String?
    public var permission: String?

    public init(id: Int64? = nil, unionID: String? = nil, phone: String? = nil, createDate: Date? = nil, userName: String? = nil, phoneIsValid: Bool? = nil, data: String? = nil, email: String? = nil, emailIsValid: Bool? = nil, lastUpdate: Date? = nil, nickName: String? = nil, avatar: String? = nil, role: String? = nil, permission: String? = nil) {
        self.id = id
        self.unionID = unionID
        self.phone = phone
        self.createDate = createDate
        self.userName = userName
        self.phoneIsValid = phoneIsValid
        self.data = data
        self.email = email
        self.emailIsValid = emailIsValid
        self.lastUpdate = lastUpdate
        self.nickName = nickName
        self.avatar = avatar
        self.role = role
        self.permission = permission
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case unionID
        case phone
        case createDate
        case userName
        case phoneIsValid
        case data
        case email
        case emailIsValid
        case lastUpdate
        case nickName
        case avatar
        case role
        case permission
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(unionID, forKey: .unionID)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(createDate, forKey: .createDate)
        try container.encodeIfPresent(userName, forKey: .userName)
        try container.encodeIfPresent(phoneIsValid, forKey: .phoneIsValid)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(emailIsValid, forKey: .emailIsValid)
        try container.encodeIfPresent(lastUpdate, forKey: .lastUpdate)
        try container.encodeIfPresent(nickName, forKey: .nickName)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(permission, forKey: .permission)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProfileResult: Identifiable {}
