//
// QRCodePreSignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QRCodePreSignInRequest: Codable, JSONEncodable, Hashable {

    public static let scopesRule = StringRule(minLength: 0, maxLength: 100, pattern: "/^[a-zA-Z0-9,]*$/")
    public static let remarkRule = StringRule(minLength: 0, maxLength: 200, pattern: nil)
    public static let schemeRule = StringRule(minLength: 0, maxLength: 50, pattern: "/^[a-zA-Z0-9]*$/")
    /** 授权范围，长度不能超过100个字符，只能包含字母、数字和逗号 */
    public var scopes: String?
    /** 备注，长度不能超过200个字符 */
    public var remark: String?
    /** 方案，长度不能超过50个字符，只能包含字母和数字 */
    public var scheme: String?

    public init(scopes: String? = nil, remark: String? = nil, scheme: String? = nil) {
        self.scopes = scopes
        self.remark = remark
        self.scheme = scheme
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case scopes
        case remark
        case scheme
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(scopes, forKey: .scopes)
        try container.encodeIfPresent(remark, forKey: .remark)
        try container.encodeIfPresent(scheme, forKey: .scheme)
    }
}

