//
// QRCodeSignUpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QRCodeSignUpRequest: Codable, JSONEncodable, Hashable {

    public static let unionIDRule = StringRule(minLength: 1, maxLength: 99, pattern: nil)
    public static let nickNameRule = StringRule(minLength: nil, maxLength: 99, pattern: nil)
    public static let avatarRule = StringRule(minLength: nil, maxLength: 999, pattern: nil)
    public static let dataRule = StringRule(minLength: nil, maxLength: 9999, pattern: nil)
    public static let emailRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,5}$/")
    public static let emailCodeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/\\d{4,8}$/")
    public static let phoneRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(\\d{11})?$/")
    public static let phoneCodeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/\\d{4,8}$/")
    public var signInKey: Int64?
    public var unionID: String
    /** 昵称 */
    public var nickName: String?
    /** 头像 */
    public var avatar: String?
    /** 自定义数据 */
    public var data: String?
    /** 邮箱 */
    public var email: String?
    /** 邮箱验证码（只有启用的邮箱验证码功能时，才需要传入） */
    public var emailCode: String?
    /** 手机号 */
    public var phone: String?
    /** 手机验证码（只有启用的手机验证码功能时，才需要传入） */
    public var phoneCode: String?

    public init(signInKey: Int64? = nil, unionID: String, nickName: String? = nil, avatar: String? = nil, data: String? = nil, email: String? = nil, emailCode: String? = nil, phone: String? = nil, phoneCode: String? = nil) {
        self.signInKey = signInKey
        self.unionID = unionID
        self.nickName = nickName
        self.avatar = avatar
        self.data = data
        self.email = email
        self.emailCode = emailCode
        self.phone = phone
        self.phoneCode = phoneCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signInKey
        case unionID
        case nickName
        case avatar
        case data
        case email
        case emailCode
        case phone
        case phoneCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(signInKey, forKey: .signInKey)
        try container.encode(unionID, forKey: .unionID)
        try container.encodeIfPresent(nickName, forKey: .nickName)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(emailCode, forKey: .emailCode)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(phoneCode, forKey: .phoneCode)
    }
}

