//
// SendEmailCodeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendEmailCodeRequest: Codable, JSONEncodable, Hashable {

    public static let emailRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let typeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var email: String
    /** 用途。可选值：signup/forgetpwd */
    public var type: String

    public init(email: String, type: String) {
        self.email = email
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(type, forKey: .type)
    }
}

