//
// SendSMSCodeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendSMSCodeRequest: Codable, JSONEncodable, Hashable {

    public static let phoneRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let typeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** 用户手机号 */
    public var phone: String
    /** 用途。可选值：signup（注册）/forgetpwd（忘记密码） */
    public var type: String

    public init(phone: String, type: String) {
        self.phone = phone
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(phone, forKey: .phone)
        try container.encode(type, forKey: .type)
    }
}

