//
// ServiceGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** 服务功能分组实体，用于对服务功能进行分类和管理。 */
public struct ServiceGroup: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 100, pattern: nil)
    public static let codeRule = StringRule(minLength: nil, maxLength: 50, pattern: nil)
    public static let iconRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    /** 服务功能分组的唯一标识符。 */
    public var id: Int64?
    /** 关联的服务商的唯一标识符。 */
    public var providerID: Int64?
    /** 服务功能分组的名称。 */
    public var name: String?
    /** 服务功能分组的唯一代码，用于系统内部标识。 */
    public var code: String?
    /** 服务功能分组的图标URL或路径。 */
    public var icon: String?
    /** 服务功能分组的详细描述信息。 */
    public var description: String?
    /** 指示服务功能分组是否在界面上显示。 */
    public var show: Bool?
    /** 服务功能分组在界面上的显示顺序。 */
    public var showIndex: Int?
    /** 服务功能分组的创建日期，默认为当前时间。 */
    public var createDate: Date?
    /** 服务功能分组的最后更新日期，默认为当前时间。 */
    public var lastUpdate: Date?

    public init(id: Int64? = nil, providerID: Int64? = nil, name: String? = nil, code: String? = nil, icon: String? = nil, description: String? = nil, show: Bool? = nil, showIndex: Int? = nil, createDate: Date? = nil, lastUpdate: Date? = nil) {
        self.id = id
        self.providerID = providerID
        self.name = name
        self.code = code
        self.icon = icon
        self.description = description
        self.show = show
        self.showIndex = showIndex
        self.createDate = createDate
        self.lastUpdate = lastUpdate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case providerID
        case name
        case code
        case icon
        case description
        case show
        case showIndex
        case createDate
        case lastUpdate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(providerID, forKey: .providerID)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(show, forKey: .show)
        try container.encodeIfPresent(showIndex, forKey: .showIndex)
        try container.encodeIfPresent(createDate, forKey: .createDate)
        try container.encodeIfPresent(lastUpdate, forKey: .lastUpdate)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceGroup: Identifiable {}
