//
// SetupCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetupCode: Codable, JSONEncodable, Hashable {

    public var account: String?
    public var manualEntryKey: String?
    public var qrCodeSetupImageUrl: String?

    public init(account: String? = nil, manualEntryKey: String? = nil, qrCodeSetupImageUrl: String? = nil) {
        self.account = account
        self.manualEntryKey = manualEntryKey
        self.qrCodeSetupImageUrl = qrCodeSetupImageUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case manualEntryKey
        case qrCodeSetupImageUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(manualEntryKey, forKey: .manualEntryKey)
        try container.encodeIfPresent(qrCodeSetupImageUrl, forKey: .qrCodeSetupImageUrl)
    }
}

