//
// SignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignInRequest: Codable, JSONEncodable, Hashable {

    public static let userNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let pwdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var userName: String
    public var pwd: String
    /** 如果启用双因素认证登录，则必填 */
    public var twoFactorCode: String?

    public init(userName: String, pwd: String, twoFactorCode: String? = nil) {
        self.userName = userName
        self.pwd = pwd
        self.twoFactorCode = twoFactorCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userName
        case pwd
        case twoFactorCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userName, forKey: .userName)
        try container.encode(pwd, forKey: .pwd)
        try container.encodeIfPresent(twoFactorCode, forKey: .twoFactorCode)
    }
}

