//
// StorageListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StorageListResult: Codable, JSONEncodable, Hashable {

    public var take: Int?
    public var skip: Int?
    public var total: Int64?
    public var data: AnyCodable?
    public var explain: AnyCodable?

    public init(take: Int? = nil, skip: Int? = nil, total: Int64? = nil, data: AnyCodable? = nil, explain: AnyCodable? = nil) {
        self.take = take
        self.skip = skip
        self.total = total
        self.data = data
        self.explain = explain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case take
        case skip
        case total
        case data
        case explain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(take, forKey: .take)
        try container.encodeIfPresent(skip, forKey: .skip)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(explain, forKey: .explain)
    }
}

