//
// SystemFileListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemFileListResult: Codable, JSONEncodable, Hashable {

    public var directories: [SystemDirectoryItem]?
    public var files: [SystemFileItem]?
    public var size: Int64?

    public init(directories: [SystemDirectoryItem]? = nil, files: [SystemFileItem]? = nil, size: Int64? = nil) {
        self.directories = directories
        self.files = files
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case directories
        case files
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(directories, forKey: .directories)
        try container.encodeIfPresent(files, forKey: .files)
        try container.encodeIfPresent(size, forKey: .size)
    }
}

