//
// TapPayInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TapPayInfo: Codable, JSONEncodable, Hashable {

    public var paymentMediumType: String?

    public init(paymentMediumType: String? = nil) {
        self.paymentMediumType = paymentMediumType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paymentMediumType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(paymentMediumType, forKey: .paymentMediumType)
    }
}

