//
// TradeFundBill.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TradeFundBill: Codable, JSONEncodable, Hashable {

    public var amount: String?
    public var bankCode: String?
    public var fundChannel: String?
    public var fundType: String?
    public var realAmount: String?

    public init(amount: String? = nil, bankCode: String? = nil, fundChannel: String? = nil, fundType: String? = nil, realAmount: String? = nil) {
        self.amount = amount
        self.bankCode = bankCode
        self.fundChannel = fundChannel
        self.fundType = fundType
        self.realAmount = realAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case bankCode
        case fundChannel
        case fundType
        case realAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(bankCode, forKey: .bankCode)
        try container.encodeIfPresent(fundChannel, forKey: .fundChannel)
        try container.encodeIfPresent(fundType, forKey: .fundType)
        try container.encodeIfPresent(realAmount, forKey: .realAmount)
    }
}

