//
// TradeSettleInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TradeSettleInfo: Codable, JSONEncodable, Hashable {

    public var tradeSettleDetailList: [TradeSettleDetail]?
    public var tradeUnsettledAmount: String?

    public init(tradeSettleDetailList: [TradeSettleDetail]? = nil, tradeUnsettledAmount: String? = nil) {
        self.tradeSettleDetailList = tradeSettleDetailList
        self.tradeUnsettledAmount = tradeUnsettledAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tradeSettleDetailList
        case tradeUnsettledAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tradeSettleDetailList, forKey: .tradeSettleDetailList)
        try container.encodeIfPresent(tradeUnsettledAmount, forKey: .tradeUnsettledAmount)
    }
}

