//
// UnionIDSignUpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UnionIDSignUpRequest: Codable, JSONEncodable, Hashable {

    public static let userNameRule = StringRule(minLength: 6, maxLength: 32, pattern: nil)
    public static let unionIDRule = StringRule(minLength: 1, maxLength: 99, pattern: "/^[a-zA-Z0-9_-]*$/")
    public static let platformRule = StringRule(minLength: 1, maxLength: 20, pattern: "/^[a-zA-Z0-9]*$/")
    public static let pwdRule = StringRule(minLength: 6, maxLength: 32, pattern: "/^[a-zA-Z0-9_\\-!@#$%^&*()]*$/")
    public static let nickNameRule = StringRule(minLength: 4, maxLength: 32, pattern: nil)
    public static let avatarRule = StringRule(minLength: nil, maxLength: 999, pattern: nil)
    public static let dataRule = StringRule(minLength: nil, maxLength: 9999, pattern: nil)
    public static let emailCodeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/\\d{4,8}$/")
    public static let phoneRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(\\d{11})?$/")
    public static let phoneCodeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/\\d{4,8}$/")
    /** 登录账号，可空，只能包含字母、数字、下划线和连字符 */
    public var userName: String?
    /** UnionID，长度不能超过99个字符，只能包含字母、数字、下划线和连字符 */
    public var unionID: String
    /** 平台标识，长度必须在1到20个字符之间，只能包含字母和数字 */
    public var platform: String
    /** 密码，长度必须在6到32个字符之间，只允许英文大小写、数字、标点符号 */
    public var pwd: String
    /** 用户昵称 */
    public var nickName: String?
    /** 用户头像URL */
    public var avatar: String?
    /** 自定义数据 */
    public var data: String?
    /** 用户邮箱 */
    public var email: String?
    /** 邮箱验证码（只有启用的邮箱验证码功能时，才需要传入），长度为4到8位的数字 */
    public var emailCode: String?
    /** 用户手机号，必须为11位数字 */
    public var phone: String?
    /** 手机验证码（只有启用的手机验证码功能时，才需要传入），长度为4到8位的数字 */
    public var phoneCode: String?

    public init(userName: String? = nil, unionID: String, platform: String, pwd: String, nickName: String? = nil, avatar: String? = nil, data: String? = nil, email: String? = nil, emailCode: String? = nil, phone: String? = nil, phoneCode: String? = nil) {
        self.userName = userName
        self.unionID = unionID
        self.platform = platform
        self.pwd = pwd
        self.nickName = nickName
        self.avatar = avatar
        self.data = data
        self.email = email
        self.emailCode = emailCode
        self.phone = phone
        self.phoneCode = phoneCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userName
        case unionID
        case platform
        case pwd
        case nickName
        case avatar
        case data
        case email
        case emailCode
        case phone
        case phoneCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userName, forKey: .userName)
        try container.encode(unionID, forKey: .unionID)
        try container.encode(platform, forKey: .platform)
        try container.encode(pwd, forKey: .pwd)
        try container.encodeIfPresent(nickName, forKey: .nickName)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(emailCode, forKey: .emailCode)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(phoneCode, forKey: .phoneCode)
    }
}

