//
// UserProfileResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserProfileResult: Codable, JSONEncodable, Hashable {

    public var user: User?
    public var currencies: [UserCurrency]?
    public var role: String?

    public init(user: User? = nil, currencies: [UserCurrency]? = nil, role: String? = nil) {
        self.user = user
        self.currencies = currencies
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case currencies
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(currencies, forKey: .currencies)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

