//
// UserMutualFollowersResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserMutualFollowersResult: Codable, JSONEncodable, Hashable {

    public var totalFollowers: Int64?
    public var data: [CommonFriendModel]?

    public init(totalFollowers: Int64? = nil, data: [CommonFriendModel]? = nil) {
        self.totalFollowers = totalFollowers
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalFollowers
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalFollowers, forKey: .totalFollowers)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

