//
// WechatJSConfigResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WechatJSConfigResult: Codable, JSONEncodable, Hashable {

    public var noncestr: String?
    public var timestamp: String?
    public var signature: String?
    public var appKey: String?
    public var jsApiList: [String]?

    public init(noncestr: String? = nil, timestamp: String? = nil, signature: String? = nil, appKey: String? = nil, jsApiList: [String]? = nil) {
        self.noncestr = noncestr
        self.timestamp = timestamp
        self.signature = signature
        self.appKey = appKey
        self.jsApiList = jsApiList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case noncestr
        case timestamp
        case signature
        case appKey
        case jsApiList
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(noncestr, forKey: .noncestr)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(signature, forKey: .signature)
        try container.encodeIfPresent(appKey, forKey: .appKey)
        try container.encodeIfPresent(jsApiList, forKey: .jsApiList)
    }
}

